#! /bin/bash

# A klutzy password manager until I can find a good one
# that works on the Raspberry pi

file=passwords

madedir=false
if [ ! -r ~/.etc ]
then
    mkdir ~/.etc
    madedir=true

fi

cd ~/.etc
case $madedir in
    true) > passwords.enc
            ;;
esac

function usage {
        echo "`basename $0`: [-ae]
        -a key password (add password assoc with key)
        -e key  (extract passwd assoc with key)
        -l (list the keys on stdout)
        -d (dump a clear text file in ~/.etc)"
        exit 1
}

trap "rm -f $file" SIGINT

case "$1" in
        -a | -add)
                shift
                if [ $# != 2 ]
                then
                    usage 
                fi
                unscramble $file
                echo "$1 $2" >> $file
                scramble $file
                ;;
                
        -e | -extract)
                cd ~/.etc
                shift
                unscramble $file 
                egrep -i "$1" $file | awk '{print $2}' | cpy
                rm -f $file
                echo "passwd in cut buffer" > /dev/stdout
                ;;
        -l | -ls | -list)
                cd ~/.etc
                shift
                unscramble $file
                awk '{print $1}' $file
                rm -f $file
                ;;

        -d | -dump)
                cd ~/.etc
                echo "Readable passwd file in ~/.etc"
                unscramble $file
                ;;

        *)
                usage
                ;;
esac
