#! /bin/bash

USAGE='-u : update (update and upgrade)
-autorm : autoremove (unneeded packages)
-i package : install package
-reinstall : force a reinstall of package with latest rev
-ls : List all installed packages
-rm packagename : Remove packagename from system'


case "$1" in
        -i | install)
                shift
                sudo apt-get install $1
                ;;

	-df)
		df -h 	# To determine how much disk space is free
		;;

        -u | -update)
                sudo apt-get update    		# Update paclage list
                sudo apt-get full-upgrade   	# Full-update for dependencies
                sudo apt autoremove
                ;;

        -autorm | autoremove)
                sudo apt autoremove
                ;;

        -reinstall)
                sudo reinstall
                ;;

        -ls)
                dpkg -l
                ;;

        -rm)
                shift
                sudo apt remove "$1"
                ;;

        *)
                echo "$USAGE"
                ;;
esac
