#! /bin/bash

USAGE='-u : update (update and upgrade)
-autorm : autoremove (unneeded packages)
-i package : install package
-reinstall : force a reinstall of package with latest rev
-ls : List all installed packages
-rm packagename : Remove packagename from system'


case "$1" in
        -i | install)
                shift
                sudo apt install $1
                ;;

        -u | -update)
                sudo apt-get update
                sudo apt-get upgrade
                sudo apt autoremove
                ;;

        -autorm | autoremove)
                sudo apt autoremove
                ;;

        -reinstall)
                sudo reinstall
                ;;

        -ls)
                dpkg -l
                ;;

        -rm)
                shift
                sudo apt remove "$1"
                ;;

        *)
                echo "$USAGE"
                ;;
esac
