#! /bin/bash

USAGE='-u : update (update and upgrade)
-r : autoremove (unneeded packages)
-i package : install package'

case "$1" in
        -i | install)
                shift
                sudo apt install $1
                ;;

        -u | -update)
                sudo apt-get update
                sudo apt-get upgrade
                ;;

        -r | autoremove)
                sudo apt autoremove
                ;;

        *)
                echo "$USAGE"
                ;;
esac
